// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sshrqbsckvnkjdoplnxx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNzaHJxYnNja3Zua2pkb3Bsbnh4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwNDMwMjAsImV4cCI6MjA1OTYxOTAyMH0.Pm_gp1rWZRD-xTwEzy-Qp9oM8patG_nRHKjrUgeDfXA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);